---
title: "Methods Paper"
author: "Sarah Bangerth"
date: "2023-06-22"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd('/users/sarahbangerth/Desktop/Github/IMC_Methods/IMC_Methods_Paper')

## Libraries
library(imcRtools)
library(cytomapper)
library(dplyr)
library(ComplexHeatmap)
library(CATALYST)
library(singleCellTK)
library(tidyverse)
library(circlize)
library(reshape2)
library(ggplot2)
library(readr)
library(ggpubr)
```

# DATA STANDARDIZATION ON BOTH DATASETS TOGETHER

```{r}
raw_sce = readRDS("Data/Human/human_raw_data_Cells.rds")
raw_sce$Data = 'Raw'

processed_sce = readRDS("Data/Human/human_preprocessed_data_Cells.rds")
processed_sce$Data = 'Pre-processed'
```


```{r}
rownames(raw_sce)[12] = 'Foxp3'
rownames(raw_sce)[16] = 'Collagen'
rowData(processed_sce)$channel = rowData(raw_sce)$channel
rowData(raw_sce)$name[12] = 'Foxp3'
rowData(raw_sce)$name[21] = 'Ir191'
rowData(raw_sce)$name[22] = 'Ir193'
rowData(raw_sce)$name[16] = 'Collagen'


sce_combined = cbind(raw_sce, processed_sce, deparse.level = 1)
assay(sce_combined,'exprs') [,1]

assay(sce_combined, "z-exprs") = asinh(counts(sce_combined)/5)

assay(sce_combined,'z-exprs') = t(scale(t(assay(sce_combined,'z-exprs'))))
assay(sce_combined,'z-exprs') [,1]
```


```{r}
markers_to_include = c('CD66b','CD20','CD28','CD16','CD163','CD11b','CD45',
                       'CD4','CD31','CD279','CD68','Foxp3','CK7','Ki67','CD8','CD3','CD138','HLADR','GranzymeB')

marker_expression <- data.frame(t(assay(sce_combined[markers_to_include,], "z-exprs")))
marker_expression$cellID <- rownames(marker_expression)
dat <- data.frame(colData(sce_combined)[,"Data"])
colnames(dat) = "Data"
dat$cellID <- rownames(marker_expression)
dat <- left_join(dat, marker_expression)
dat$cellID <- NULL
head(dat)

dat_aggr <- dat %>%
  group_by(Data) %>%
  summarise_all(funs(median))

dat_sum <- dat %>%
  group_by(Data) %>%
  dplyr::summarise(n=n())

rownames(dat_sum) = dat_sum$Data
dat_sum <- data.frame(t(dat_sum))
m <- as.matrix((dat_aggr[,-c(1)]))
rownames(m) <- dat_aggr$Data

ha_right <- rowAnnotation(" " = anno_barplot((as.numeric(dat_sum[2,])),
                                                     add_numbers = TRUE,numbers_gp = gpar(fontsize = 20),
                                                     which = "row",
                                                     numbers_rot=0,
                                                     ylim=c(0,300000),
                                                     axis=FALSE,
                                                     border=FALSE,
                                                     width = unit(3, "cm")))

scaled_heatmap = Heatmap(m, name = "Scaled expression",border='black',
                                  cluster_columns = FALSE,
                                  show_column_dend = FALSE,
                                  cluster_rows = FALSE,
                                  show_row_dend = FALSE,
                                  column_names_rot = 90,
                                  column_names_centered = FALSE,
                                  show_column_names = TRUE,
                                  row_title_gp = gpar(fontsize = 23), #23
                                  row_names_gp = gpar(fontsize = 25),
                                  column_names_gp = gpar(fontsize = 25),
                                  right_annotation = ha_right,
                                  rect_gp = gpar(col = "white", lwd = 2),
                                  col = colorRamp2(c(-1, 1), hcl_palette='viridis'),
                                  heatmap_legend_param = list(at = c(-1:1), legend_width = unit(6,"cm"),
                                                              direction="horizontal", title_gp = gpar(fontsize=12),
                                                              title_position = "topcenter",
                                                              labels_gp = gpar(fontsize=12)),
                                  column_names_side = "bottom",
                                  row_names_side = 'left',
                                  height = unit(5, "cm"),
                                  width = unit(28,"cm"))

draw(scaled_heatmap, heatmap_legend_side = "top")
```

T-sne

```{r}
markers_to_include = c('CD66b','CD20','CD28','CD16','CD163','CD11b','CD45',
                       'CD4','CD31','CD279','CD68','Foxp3','CK7','Ki67','CD8','CD3','CD138','HLADR','GranzymeB')

set.seed(88)
sce_combined = runDR(sce_combined, "TSNE", features = markers_to_include) 

# Save object with tsne results for future use
exportSCE(sce_combined, samplename = "sce_combined_IMC_methods", directory = "./",
          type = "Cells",format = "SCE")
# sce_combined = readRDS("/users/sarahbangerth/Desktop/IMC/Methods Paper/sce_combined_IMC_methods/R/sce_combined_IMC_methods_Cells.rds")

sce_combined$Clusters = factor(sce_combined$Clusters,
                               levels=c('CD4+ T-cells', 'CD8+ T-cells', 'Macrophages', 'Monocytes', 'B cells', 'Neutrophils',
                                        'Plasma cells', 'Cholangiocytes', 'Endothelial cells', 'Hepatocytes'))

# Facet by clinical group, but excluding Hepatocytes
sce_combined_noHep = sce_combined[,sce_combined$Clusters != 'Hepatocytes']
sce_combined_noHep$Clusters = factor(sce_combined_noHep$Clusters,
                               levels=c('CD4+ T-cells', 'CD8+ T-cells', 'Macrophages', 'Monocytes', 'B cells', 'Neutrophils',
                                        'Plasma cells', 'Cholangiocytes', 'Endothelial cells', 'Hepatocytes'))

plotDR(sce_combined_noHep[,sce_combined_noHep$Data=='Raw'], "TSNE", color_by = "Clusters", facet_by = 'group') +
  xlab("tSNE 1") + ylab("tSNE 2") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.title=element_text(size=20),
        strip.text=element_text(size = 28, hjust = 0.5),
        aspect.ratio=1,
        legend.position='bottom',
        legend.title=element_blank(),
        legend.text=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 6))) +
  scale_color_manual(values=c("#C04000","orange","#0096FF","green","#bf812d",
                              "#ae017e","#CCCCFF","#FFEA00","#313695"))
                              
plotDR(sce_combined_noHep[,sce_combined_noHep$Data=='Pre-processed'], "TSNE", color_by = "Clusters", facet_by = 'group') +
  xlab("tSNE 1") + ylab("tSNE 2") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.title=element_text(size=20),
        strip.text=element_text(size = 28, hjust = 0.5),
        aspect.ratio=1,
        legend.position='bottom',
        legend.title=element_blank(),
        legend.text=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 6))) +
  scale_color_manual(values=c("#C04000","orange","#0096FF","green","#bf812d",
                              "#ae017e","#CCCCFF","#FFEA00","#313695"))
                  
            
# CD4+ Cells #
plotDR(sce_combined[,(sce_combined$Data=='Raw')&(sce_combined$Clusters=='CD4+ T-cells')], "TSNE", 
       color_by = "Subcluster", facet_by = 'group') +
  xlab("tSNE 1") + ylab("tSNE 2") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.title=element_text(size=20),
        strip.text=element_text(size = 28, hjust = 0.5),
        aspect.ratio=1,
        legend.position='bottom',
        legend.title=element_blank(),
        legend.text=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 4), nrow=5)) +
  scale_color_manual(values=c("#bf812d","#00ffff","#FFEA00", ##014421
                              "#7F00FF","#ae017e","#6a87a3","#0096FF",#"#ff77ff",
                              'orange'))
                              
plotDR(sce_combined[,(sce_combined$Data=='Pre-processed')&(sce_combined$Clusters=='CD4+ T-cells')], "TSNE", 
       color_by = "Subcluster", facet_by = 'group') +
  xlab("tSNE 1") + ylab("tSNE 2") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.title=element_text(size=20),
        strip.text=element_text(size = 28, hjust = 0.5),
        aspect.ratio=1,
        legend.position='bottom',
        legend.title=element_blank(),
        legend.text=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 4), nrow=5)) +
  scale_color_manual(values=c("#bf812d","#00ffff","#FFEA00", ##014421
                              "#7F00FF","#ae017e","#6a87a3","#0096FF","#ff77ff",'orange'))
                              
# CD8+ Cells #
plotDR(sce_combined[,(sce_combined$Data=='Raw')&(sce_combined$Clusters=='CD8+ T-cells')], "TSNE", 
       color_by = "Subcluster", facet_by = 'group') +
  xlab("tSNE 1") + ylab("tSNE 2") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.title=element_text(size=20),
        strip.text=element_text(size = 28, hjust = 0.5),
        aspect.ratio=1,
        legend.position='bottom',
        legend.title=element_blank(),
        legend.text=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 4), nrow=2)) +
  scale_color_manual(values=c("orange","#FFEA00","#0096FF","#ff77ff"))
                              
plotDR(sce_combined[,(sce_combined$Data=='Pre-processed')&(sce_combined$Clusters=='CD8+ T-cells')], "TSNE", 
       color_by = "Subcluster", facet_by = 'group') +
  xlab("tSNE 1") + ylab("tSNE 2") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.title=element_text(size=20),
        strip.text=element_text(size = 28, hjust = 0.5),
        aspect.ratio=1,
        legend.position='bottom',
        legend.title=element_blank(),
        legend.text=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 4), nrow=2)) +
  scale_color_manual(values=c("#FFEA00","#ae017e","#bf812d","#0096FF","#ff77ff"))

# Macrophages #
plotDR(sce_combined[,(sce_combined$Data=='Raw')&(sce_combined$Clusters=='Macrophages')], "TSNE", 
       color_by = "Subcluster", facet_by = 'group') +
  xlab("tSNE 1") + ylab("tSNE 2") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.title=element_text(size=20),
        strip.text=element_text(size = 28, hjust = 0.5),
        aspect.ratio=1,
        legend.position='bottom',
        legend.title=element_blank(),
        legend.text=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 4), nrow=5)) +
  scale_color_manual(values=c("#6a87a3","#ccff00","#FFEA00", 
                              "#0096FF","#313695","#8b008b","#ff77ff"))
                              
plotDR(sce_combined[,(sce_combined$Data=='Pre-processed')&(sce_combined$Clusters=='Macrophages')], "TSNE", 
       color_by = "Subcluster", facet_by = 'group') +
  xlab("tSNE 1") + ylab("tSNE 2") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.title=element_text(size=20),
        strip.text=element_text(size = 28, hjust = 0.5),
        aspect.ratio=1,
        legend.position='bottom',
        legend.title=element_blank(),
        legend.text=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 4), nrow=5)) +
  scale_color_manual(values=c("#dfc27d","#bf812d","#6a87a3","#ccff00","#FFEA00", 
                              "#0096FF","#313695","#8b008b","#ff77ff"))
                              
# Monocytes #
plotDR(sce_combined[,(sce_combined$Data=='Raw')&(sce_combined$Clusters=='Monocytes')], "TSNE", 
       color_by = "Subcluster", facet_by = 'group') +
  xlab("tSNE 1") + ylab("tSNE 2") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.title=element_text(size=20),
        strip.text=element_text(size = 28, hjust = 0.5),
        aspect.ratio=1,
        legend.position='bottom',
        legend.title=element_blank(),
        legend.text=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 4), nrow=2)) +
  scale_color_manual(values=c("#0096FF","#FFEA00","#ae017e","#ff77ff"))

plotDR(sce_combined[,(sce_combined$Data=='Pre-processed')&(sce_combined$Clusters=='Monocytes')], "TSNE", 
       color_by = "Subcluster", facet_by = 'group') +
  xlab("tSNE 1") + ylab("tSNE 2") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.title=element_text(size=20),
        strip.text=element_text(size = 28, hjust = 0.5),
        aspect.ratio=1,
        legend.position='bottom',
        legend.title=element_blank(),
        legend.text=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 4), nrow=2)) +
  scale_color_manual(values=c("#0096FF","#bf812d","#ae017e","#FFEA00"))

# B Cells #
plotDR(sce_combined[,(sce_combined$Data=='Raw')&(sce_combined$Clusters=='B cells')], "TSNE", 
       color_by = "Subcluster", facet_by = 'group') +
  xlab("tSNE 1") + ylab("tSNE 2") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.title=element_text(size=20),
        strip.text=element_text(size = 28, hjust = 0.5),
        aspect.ratio=1,
        legend.position='bottom',
        legend.title=element_blank(),
        legend.text=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 4))) +
  scale_color_manual(values=c("#FFEA00","#0096FF","#ff77ff"))

plotDR(sce_combined[,(sce_combined$Data=='Pre-processed')&(sce_combined$Clusters=='B cells')], "TSNE", 
       color_by = "Subcluster", facet_by = 'group') +
  xlab("tSNE 1") + ylab("tSNE 2") +
  theme(panel.grid=element_blank(),
        axis.text=element_blank(),
        axis.title=element_text(size=20),
        strip.text=element_text(size = 28, hjust = 0.5),
        aspect.ratio=1,
        legend.position='bottom',
        legend.title=element_blank(),
        legend.text=element_text(size=20)) +
  guides(color = guide_legend(override.aes = list(size = 4))) +
  scale_color_manual(values=c("#FFEA00","#0096FF","#ff77ff"))
```

```{r}
colData(sce_combined[,sce_combined$Data=='Raw'])
data_raw = cbind(as.data.frame(colData(sce_combined[,sce_combined$Data=='Raw'])$sample_id), as.data.frame(colData(sce_combined[,sce_combined$Data=='Raw'])$ObjectNumber))
colnames(data_raw) = c('ImgID','CellID')

head(data_raw)

data_raw$CD66b = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[1,]
data_raw$CD20 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[2,]
data_raw$CD28 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[3,]
data_raw$CD16 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[4,]
data_raw$CD163 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[5,]
data_raw$CD11b = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[6,]
data_raw$CD45 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[7,]
data_raw$CD4 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[8,]
data_raw$CD31 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[9,]
data_raw$CD279 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[10,]
data_raw$CD68 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[11,]
data_raw$Foxp3 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[12,]
data_raw$CK7 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[13,]
data_raw$Ki67 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[14,]
data_raw$CD8 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[15,]
data_raw$CollagenI = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[16,]
data_raw$CD3 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[17,]
data_raw$CD138 = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[18,]
data_raw$HLADR = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[19,]
data_raw$GranzymeB = assay(sce_combined[,sce_combined$Data=='Raw'], "z-exprs")[20,]
data_raw$group = colData(sce_combined[,sce_combined$Data=='Raw'])$group
data_raw$Clusters = sce_combined[,sce_combined$Data=='Raw']$Clusters
data_raw$Subcluster = sce_combined[,sce_combined$Data=='Raw']$Subcluster
data_raw$ROI = sce_combined[,sce_combined$Data=='Raw']$sample_id
data_raw$Patient = sce_combined[,sce_combined$Data=='Raw']$Patient
head(data_raw)
dim(data_raw)

colData(sce_combined[,sce_combined$Data=='Pre-processed'])
data_processed = cbind(as.data.frame(colData(sce_combined[,sce_combined$Data=='Pre-processed'])$sample_id), as.data.frame(colData(sce_combined[,sce_combined$Data=='Pre-processed'])$ObjectNumber))
colnames(data_processed) = c('ImgID','CellID')

head(data_processed)

data_processed$CD66b = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[1,]
data_processed$CD20 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[2,]
data_processed$CD28 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[3,]
data_processed$CD16 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[4,]
data_processed$CD163 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[5,]
data_processed$CD11b = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[6,]
data_processed$CD45 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[7,]
data_processed$CD4 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[8,]
data_processed$CD31 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[9,]
data_processed$CD279 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[10,]
data_processed$CD68 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[11,]
data_processed$Foxp3 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[12,]
data_processed$CK7 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[13,]
data_processed$Ki67 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[14,]
data_processed$CD8 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[15,]
data_processed$CollagenI = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[16,]
data_processed$CD3 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[17,]
data_processed$CD138 = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[18,]
data_processed$HLADR = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[19,]
data_processed$GranzymeB = assay(sce_combined[,sce_combined$Data=='Pre-processed'], "z-exprs")[20,]
data_processed$group = colData(sce_combined[,sce_combined$Data=='Pre-processed'])$group
data_processed$Clusters = sce_combined[,sce_combined$Data=='Pre-processed']$Clusters
data_processed$Subcluster = sce_combined[,sce_combined$Data=='Pre-processed']$Subcluster
data_processed$ROI = sce_combined[,sce_combined$Data=='Pre-processed']$sample_id
data_processed$Patient = processed_sce$Patient
head(data_processed)
dim(data_processed)
```

# METACLUSTER COMPARISON

```{r}
#################################################
# Calculate median marker expression by Cluster #
#################################################

data_raw_median = data_raw %>% group_by(Clusters) %>% 
  dplyr::summarize(CD66b=median(CD66b),CD20=median(CD20),CD28=median(CD28),CD16=median(CD16),
                   CD163=median(CD163),CD11b=median(CD11b),CD45=median(CD45),CD4=median(CD4),
                   CD31=median(CD31),CD279=median(CD279),CD68=median(CD68),Foxp3=median(Foxp3),
                   CK7=median(CK7),Ki67=median(Ki67),CD8=median(CD8),
                   CD3=median(CD3),CD138=median(CD138),HLADR=median(HLADR),GranzymeB=median(GranzymeB))
head(data_raw_median)

data_raw_median.melt = reshape2::melt(data_raw_median, id.vars = c('Clusters'), 
                           measure.vars = c('CD66b','CD20','CD28','CD16','CD11b','CD45','CD31','CD279',
                                            'Foxp3','CK7','Ki67','CD8','CD4','CD163','CD68','CD3',
                                            'CD138','HLADR','GranzymeB'))

data_processed_median = data_processed %>% group_by(Clusters) %>% 
  dplyr::summarize(CD66b=median(CD66b),CD20=median(CD20),CD28=median(CD28),CD16=median(CD16),
                   CD163=median(CD163),CD11b=median(CD11b),CD45=median(CD45),CD4=median(CD4),
                   CD31=median(CD31),CD279=median(CD279),CD68=median(CD68),Foxp3=median(Foxp3),
                   CK7=median(CK7),Ki67=median(Ki67),CD8=median(CD8),
                   CD3=median(CD3),CD138=median(CD138),HLADR=median(HLADR),GranzymeB=median(GranzymeB))
head(data_processed_median)

data_processed_median.melt = reshape2::melt(data_processed_median, id.vars = c('Clusters'), 
                           measure.vars = c('CD66b','CD20','CD28','CD16','CD11b','CD45','CD31','CD279',
                                            'Foxp3','CK7','Ki67','CD8','CD4','CD163','CD68','CD3',
                                            'CD138','HLADR','GranzymeB'))

data_median = merge(data_raw_median.melt,data_processed_median.melt,by=c('Clusters','variable'))
head(data_median)
data_median$FC = data_median$value.y - data_median$value.x
head(data_median)

data_median$Relative_Change = (data_median$value.y - data_median$value.x)/data_median$value.x
head(data_median)

data_median = data_median %>% mutate(Color = case_when(FC > 0 ~ 'UP',
                                                 FC < 0 ~ 'DOWN',
                                                 FC == 0 ~ 'NONE'))

# Expression fold-change per patient
ggplot(data_median, 
       aes(Clusters,variable, fill = Color, size = abs(FC))) +
  geom_point(shape = 21, stroke = 0) +
  scale_fill_manual(values = c("#313695","#FFEA00")) +
  theme_minimal() +
  theme(legend.position = "bottom", 
        axis.text=element_text(size=20),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5)) +
  guides(size = guide_legend(override.aes = list(fill = NA, color = "black", stroke = .25), 
                             label.position = "bottom",
                             title.position = "right", 
                             order = 1),
         fill = guide_colorbar(ticks.colour = NA, title.position = "top", order = 2)) +
  labs(size = "Absolute Median Fold Change", fill = "Expression", x = NULL, y = NULL)

ggplot(data = (data_median %>% filter(!variable %in% c('CD45','CD3','CD138','CK7','CD31','CD66b')) %>%
                 filter(!is.na(FC))),
       aes(x = FC, y = variable)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~Clusters)+
  ggtitle(NULL) + ylab(NULL) + xlab("Median Fold Change") +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20),
        plot.title=element_text(size = 34, hjust = 0.5),
        legend.position='none',
        panel.grid = element_blank(),
        aspect.ratio=1.6,
        strip.text=element_text(size = 10, hjust = 0.5),
        axis.ticks = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  geom_vline(xintercept = 0, color="black", lwd=1)


###################################################################################################
# For each metacluster: Calculate percentage of each marker that has a positive scaled expression #
###################################################################################################

data_raw_sum = data_raw %>% group_by(Clusters) %>% 
  dplyr::summarize(CD66b = sum(CD66b>0),CD20=sum(CD20>0),CD28=sum(CD28>0),CD16=sum(CD16>0),
                   CD163=sum(CD163>0),CD11b=sum(CD11b>0),CD45=sum(CD45>0),CD4=sum(CD4>0),
                   CD31=sum(CD31>0),CD279=sum(CD279>0),CD68=sum(CD68>0),Foxp3=sum(Foxp3>0),
                   CK7=sum(CK7>0),Ki67=sum(Ki67>0),CD8=sum(CD8>0),
                   CD3=sum(CD3>0),CD138=sum(CD138>0),HLADR=sum(HLADR>0),GranzymeB=sum(GranzymeB>0))

data_raw_sum.melt = reshape2::melt(data_raw_sum, id.vars = c('Clusters'), 
                           measure.vars = c('CD66b','CD20','CD28','CD16','CD11b','CD45','CD31','CD279',
                                            'Foxp3','CK7','Ki67','CD8','CD4','CD163','CD68','CD3',
                                            'CD138','HLADR','GranzymeB'))

data_raw_sum.melt$Perc_Positive = data_raw_sum.melt$value / dim(raw_sce)[2] * 100

data_processed_sum = data_processed %>% group_by(Clusters) %>% 
  dplyr::summarize(CD66b = sum(CD66b>0),CD20=sum(CD20>0),CD28=sum(CD28>0),CD16=sum(CD16>0),
                   CD163=sum(CD163>0),CD11b=sum(CD11b>0),CD45=sum(CD45>0),CD4=sum(CD4>0),
                   CD31=sum(CD31>0),CD279=sum(CD279>0),CD68=sum(CD68>0),Foxp3=sum(Foxp3>0),
                   CK7=sum(CK7>0),Ki67=sum(Ki67>0),CD8=sum(CD8>0),
                   CD3=sum(CD3>0),CD138=sum(CD138>0),HLADR=sum(HLADR>0),GranzymeB=sum(GranzymeB>0))

data_processed_sum.melt = reshape2::melt(data_processed_sum, id.vars = c('Clusters'), 
                           measure.vars = c('CD66b','CD20','CD28','CD16','CD11b','CD45','CD31','CD279',
                                            'Foxp3','CK7','Ki67','CD8','CD4','CD163','CD68','CD3',
                                            'CD138','HLADR','GranzymeB'))

data_processed_sum.melt$Perc_Positive = data_processed_sum.melt$value / dim(processed_sce)[2] * 100

data_sum = merge(data_raw_sum.melt,data_processed_sum.melt,by=c('Clusters','variable'))
head(data_sum)

data_sum$Relative_Change = (data_sum$Perc_Positive.y - data_sum$Perc_Positive.x)/data_sum$Perc_Positive.x
head(data_sum)

data_sum$Clusters = factor(data_sum$Clusters,
                           levels=c('Hepatocytes','Endothelial cells','Cholangiocytes','Plasma cells','Neutrophils',
                                    'B cells','Monocytes','Macrophages','CD8+ T-cells','CD4+ T-cells'))

data_sum$variable = factor(data_sum$variable,
                             levels=c('CD4','CD8','CD3','CD45','Foxp3','GranzymeB','CD28','CD279','Ki67',
                             'CD68','CD163','HLADR','CD16','CD11b','CD66b','CD20','CD31','CK7','CD138'))

# Positive marker expression by cluster, with relative change between raw and pre-processed
ggplot(data_sum, 
       aes(Clusters,variable, fill = Relative_Change, size = Perc_Positive.y)) +
  geom_point(shape = 21, stroke = 0) +
  scale_radius(range = c(5, 20)) +
  scale_fill_gradient2(high = "red",mid = "gray",low = "blue",midpoint = 0) +
  theme_bw() +
  theme(legend.position = "bottom", 
        panel.grid.major = element_blank(),
        axis.text=element_text(size=18),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        axis.ticks = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  coord_flip() +
  guides(size = guide_legend(override.aes = list(fill = NA, color = "black", stroke = .25), 
                             label.position = "bottom",
                             title.position = "right", 
                             order = 1),
         fill = guide_colorbar(ticks.colour = NA, title.position = "top", order = 2)) +
  labs(size = "Positive marker percentage\nin a cell phenotype in\npre-processed data (%)", 
       fill = "Relative change\nafter pre-processing (%)", x = NULL, y = NULL)

#############################################################################################################
# For each metacluster: Calculate ratio of  positive marker expression in one cluster vs all other clusters #
#############################################################################################################

head(data_raw_sum.melt) # value here is number of cells that have a positive expression of that corresponding marker

data_raw_sum.melt_total = data_raw_sum.melt %>% group_by(variable) %>% dplyr::summarize(TotalPositive = sum(value))
head(data_raw_sum.melt_total)

data_raw_sum.ratio = merge(data_raw_sum.melt_total,data_raw_sum.melt,by='variable')
data_raw_sum.ratio[5] = NULL
data_raw_sum.ratio$Ratio = data_raw_sum.ratio$value / data_raw_sum.ratio$TotalPositive

data_raw_sum.ratio_info = data_raw_sum.ratio[,c('variable','Clusters','Ratio')]
colnames(data_raw_sum.ratio_info) = c('variable','Clusters','Ratio_Raw')


head(data_processed_sum.melt) # value here is number of cells that have a positive expression of that corresponding marker

data_processed_sum.melt_total = data_processed_sum.melt %>% group_by(variable) %>% dplyr::summarize(TotalPositive = sum(value))

data_processed_sum.ratio = merge(data_processed_sum.melt_total,data_processed_sum.melt,by='variable')
data_processed_sum.ratio[5] = NULL
data_processed_sum.ratio$Ratio = data_processed_sum.ratio$value / data_processed_sum.ratio$TotalPositive

data_processed_sum.ratio_info = data_processed_sum.ratio[,c('variable','Clusters','Ratio')]
colnames(data_processed_sum.ratio_info) = c('variable','Clusters','Ratio_Processed')

data_ratio = merge(data_raw_sum.ratio_info,data_processed_sum.ratio_info, by=c('variable','Clusters'))
data_ratio$Ratio_Relative_Change = (data_ratio$Ratio_Processed - data_ratio$Ratio_Raw)/data_ratio$Ratio_Raw

data_ratio = data_ratio %>% mutate(Color = case_when(Ratio_Relative_Change > 0 ~ 'UP',
                                                 Ratio_Relative_Change < 0 ~ 'DOWN',
                                                 Ratio_Relative_Change == 0 ~ 'NONE'))

write_csv(data_ratio, "Metaclusters_ratio_specificity.csv")

data_ratio$Clusters = factor(data_ratio$Clusters,
                           levels=c('Hepatocytes','Endothelial cells','Cholangiocytes','Plasma cells','Neutrophils',
                                    'B cells','Monocytes','Macrophages','CD8+ T-cells','CD4+ T-cells'))

data_ratio$variable = factor(data_ratio$variable,
                             levels=c('CD4','CD8','CD3','CD45','Foxp3','GranzymeB','CD28','CD279','Ki67',
                             'CD68','CD163','HLADR','CD16','CD11b','CD66b','CD20','CD31','CK7','CD138'))

ggplot(data = (data_ratio %>% filter(variable %in% c('CD4','CD3','CD8','CD45','CD28','CD279','Foxp3','GranzymeB',
                                                     'Ki67','CD68','CD163','HLADR','CD16','CD11b','CD66b',
                                                     'CD31','CD138'))),
                       aes(x = Clusters, y = Ratio_Relative_Change,
                           fill=Color)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~variable, ncol=6) +
  ggtitle(NULL) + xlab("") + ylab("Relative change after pre-processing (%)") +
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=13),
        plot.title=element_text(size = 34, hjust = 0.5),
        panel.grid=element_blank(),
        legend.position='none',
        aspect.ratio=1.1,
        strip.text=element_text(size = 15, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5)) +
  coord_flip() +
  geom_hline(yintercept = 0, color="black", lwd=1) +
  scale_fill_manual(values = c("gray","orange"))

ggplot(data = (data_ratio %>% filter(variable %in% c('CD20','CK7'))),
                       aes(x = Clusters, y = Ratio_Relative_Change,
                           fill=Color)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~variable, ncol=5) +
  ggtitle(NULL) + xlab("") + ylab("Relative change after pre-processing (%)") +
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=13),
        plot.title=element_text(size = 34, hjust = 0.5),
        panel.grid=element_blank(),
        legend.position='none',
        aspect.ratio=1.1,
        strip.text=element_text(size = 15, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 1, hjust=0.5)) +
  coord_flip() +
  geom_hline(yintercept = 0, color="black", lwd=1) +
  scale_fill_manual(values = c("gray","orange"))

##########################################
# Count of cells total (relative change) #
##########################################

cells_per_Patient_raw = data_raw %>% subset(select=c('Patient')) %>% group_by(Patient) %>% 
  dplyr::summarise(n = n())

cellType_per_Patient_raw = data_raw %>% subset(select=c('Patient','Clusters')) %>%
  group_by(Patient,Clusters) %>% dplyr::summarise(n = n())

cells_Patient_raw = merge(cells_per_Patient_raw, cellType_per_Patient_raw, all.x=TRUE, by='Patient')
head(cells_Patient_raw)
colnames(cells_Patient_raw) = c('Patient','CellTotal','Clusters','Count')
cells_Patient_raw$Perc_CellType_Patient = cells_Patient_raw$Count / cells_Patient_raw$CellTotal
head(cells_Patient_raw)

cells_Patient_raw_md = cells_Patient_raw %>% group_by(Clusters) %>% dplyr::summarise(Median = median(Perc_CellType_Patient))
head(cells_Patient_raw_md)


cells_per_Patient_processed = data_processed %>% subset(select=c('Patient')) %>% group_by(Patient) %>% 
  dplyr::summarise(n = n())

cellType_per_Patient_processed = data_processed %>% subset(select=c('Patient','Clusters')) %>%
  group_by(Patient,Clusters) %>% dplyr::summarise(n = n())

cells_Patient_processed = merge(cells_per_Patient_processed, cellType_per_Patient_processed, all.x=TRUE, by='Patient')
head(cells_Patient_processed)
colnames(cells_Patient_processed) = c('Patient','CellTotal','Clusters','Count')
cells_Patient_processed$Perc_CellType_Patient = cells_Patient_processed$Count / cells_Patient_processed$CellTotal
head(cells_Patient_processed)

cells_Patient_processed_md = cells_Patient_processed %>% group_by(Clusters) %>% dplyr::summarise(Median = median(Perc_CellType_Patient))
head(cells_Patient_processed_md)


data_Patient_median = merge(cells_Patient_raw_md,cells_Patient_processed_md,by=c('Clusters'))
head(data_Patient_median)

data_Patient_median$Relative_Change = (data_Patient_median$Median.y -
                                         data_Patient_median$Median.x)/data_Patient_median$Median.x
head(data_Patient_median)

data_Patient_median$Clusters = factor(data_Patient_median$Clusters,
                           levels=c('Hepatocytes','Endothelial cells','Cholangiocytes','Plasma cells','Neutrophils',
                                    'B cells','Monocytes','Macrophages','CD8+ T-cells','CD4+ T-cells'))

ggplot(data = data_Patient_median,
                       aes(x = Clusters, y = Relative_Change,
                           fill=Clusters)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  ggtitle(NULL) + xlab("") + ylab("Relative change\nafter pre-processing(%)") +
  theme(axis.text=element_text(size=20),
        axis.title=element_text(size=25),
        plot.title=element_text(size = 34, hjust = 0.5),
        panel.grid=element_blank(),
        legend.position='none',
        aspect.ratio=1.2,
        strip.text=element_text(size = 34, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  geom_hline(yintercept = 0, color="black", lwd=1) +
  coord_flip() +
  scale_fill_manual(values = c("lightblue","#313695","#FFEA00","#CCCCFF","#ae017e",
                               "#bf812d","green","#0096FF","orange","#C04000"))
```

# SUBCLUSTER COMPARISON

```{r}
####################################################
# Calculate median marker expression by Subcluster #
####################################################

data_raw_median = data_raw %>% group_by(Subcluster) %>% 
  dplyr::summarize(CD66b=median(CD66b),CD20=median(CD20),CD28=median(CD28),CD16=median(CD16),
                   CD163=median(CD163),CD11b=median(CD11b),CD45=median(CD45),CD4=median(CD4),
                   CD31=median(CD31),CD279=median(CD279),CD68=median(CD68),Foxp3=median(Foxp3),
                   CK7=median(CK7),Ki67=median(Ki67),CD8=median(CD8),
                   CD3=median(CD3),CD138=median(CD138),HLADR=median(HLADR),GranzymeB=median(GranzymeB))
head(data_raw_median)

data_raw_median.melt = reshape2::melt(data_raw_median, id.vars = c('Subcluster'), 
                           measure.vars = c('CD66b','CD20','CD28','CD16','CD11b','CD45','CD31','CD279',
                                            'Foxp3','CK7','Ki67','CD8','CD4','CD163','CD68','CD3',
                                            'CD138','HLADR','GranzymeB'))

data_processed_median = data_processed %>% group_by(Subcluster) %>% 
  dplyr::summarize(CD66b=median(CD66b),CD20=median(CD20),CD28=median(CD28),CD16=median(CD16),
                   CD163=median(CD163),CD11b=median(CD11b),CD45=median(CD45),CD4=median(CD4),
                   CD31=median(CD31),CD279=median(CD279),CD68=median(CD68),Foxp3=median(Foxp3),
                   CK7=median(CK7),Ki67=median(Ki67),CD8=median(CD8),
                   CD3=median(CD3),CD138=median(CD138),HLADR=median(HLADR),GranzymeB=median(GranzymeB))
head(data_processed_median)

data_processed_median.melt = reshape2::melt(data_processed_median, id.vars = c('Subcluster'), 
                           measure.vars = c('CD66b','CD20','CD28','CD16','CD11b','CD45','CD31','CD279',
                                            'Foxp3','CK7','Ki67','CD8','CD4','CD163','CD68','CD3',
                                            'CD138','HLADR','GranzymeB'))

data_median = merge(data_raw_median.melt,data_processed_median.melt,by=c('Subcluster','variable'))
head(data_median)
data_median$FC = data_median$value.y - data_median$value.x
head(data_median)

data_median = data_median %>% mutate(Color = case_when(FC > 0 ~ 'UP',
                                                 FC < 0 ~ 'DOWN',
                                                 FC == 0 ~ 'NONE'))

# Expression fold-change per patient
ggplot(data_median, 
       aes(Subcluster,variable, fill = Color, size = abs(FC))) +
  geom_point(shape = 21, stroke = 0) +
  scale_fill_manual(values = c("#313695","#FFEA00")) +
  theme_minimal() +
  theme(legend.position = "bottom", 
        axis.text=element_text(size=15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  guides(size = guide_legend(override.aes = list(fill = NA, color = "black", stroke = .25), 
                             label.position = "bottom",
                             title.position = "right", 
                             order = 1),
         fill = guide_colorbar(ticks.colour = NA, title.position = "top", order = 2)) +
  labs(size = "Absolute Median Fold Change", fill = "Expression", x = NULL, y = NULL)


###########################################################################################################
# For each subcluster: Calculate ratio of positive marker expression in one cluster vs all other clusters #
###########################################################################################################

data_raw_sum = data_raw %>% group_by(Subcluster) %>% 
  dplyr::summarize(CD66b = sum(CD66b>0),CD20=sum(CD20>0),CD28=sum(CD28>0),CD16=sum(CD16>0),
                   CD163=sum(CD163>0),CD11b=sum(CD11b>0),CD45=sum(CD45>0),CD4=sum(CD4>0),
                   CD31=sum(CD31>0),CD279=sum(CD279>0),CD68=sum(CD68>0),Foxp3=sum(Foxp3>0),
                   CK7=sum(CK7>0),Ki67=sum(Ki67>0),CD8=sum(CD8>0),
                   CD3=sum(CD3>0),CD138=sum(CD138>0),HLADR=sum(HLADR>0),GranzymeB=sum(GranzymeB>0))

data_raw_sum.melt = reshape2::melt(data_raw_sum, id.vars = c('Subcluster'), 
                           measure.vars = c('CD66b','CD20','CD28','CD16','CD11b','CD45','CD31','CD279',
                                            'Foxp3','CK7','Ki67','CD8','CD4','CD163','CD68','CD3',
                                            'CD138','HLADR','GranzymeB'))


data_processed_sum = data_processed  %>% group_by(Subcluster) %>% 
  dplyr::summarize(CD66b = sum(CD66b>0),CD20=sum(CD20>0),CD28=sum(CD28>0),CD16=sum(CD16>0),
                   CD163=sum(CD163>0),CD11b=sum(CD11b>0),CD45=sum(CD45>0),CD4=sum(CD4>0),
                   CD31=sum(CD31>0),CD279=sum(CD279>0),CD68=sum(CD68>0),Foxp3=sum(Foxp3>0),
                   CK7=sum(CK7>0),Ki67=sum(Ki67>0),CD8=sum(CD8>0),
                   CD3=sum(CD3>0),CD138=sum(CD138>0),HLADR=sum(HLADR>0),GranzymeB=sum(GranzymeB>0))

data_processed_sum.melt = reshape2::melt(data_processed_sum, id.vars = c('Subcluster'), 
                           measure.vars = c('CD66b','CD20','CD28','CD16','CD11b','CD45','CD31','CD279',
                                            'Foxp3','CK7','Ki67','CD8','CD4','CD163','CD68','CD3',
                                            'CD138','HLADR','GranzymeB'))

head(data_raw_sum.melt) # value here is number of cells that have a positive expression of that corresponding marker

data_raw_sum.melt_total = data_raw_sum.melt %>% group_by(variable) %>% dplyr::summarize(TotalPositive = sum(value))
head(data_raw_sum.melt_total)

data_raw_sum.ratio = merge(data_raw_sum.melt_total,data_raw_sum.melt,by='variable')
data_raw_sum.ratio[5] = NULL
data_raw_sum.ratio$Ratio = data_raw_sum.ratio$value / data_raw_sum.ratio$TotalPositive

data_raw_sum.ratio_info = data_raw_sum.ratio[,c('variable','Subcluster','Ratio')]
colnames(data_raw_sum.ratio_info) = c('variable','Subcluster','Ratio_Raw')


head(data_processed_sum.melt) # value here is number of cells that have a positive expression of that corresponding marker

data_processed_sum.melt_total = data_processed_sum.melt %>% group_by(variable) %>% dplyr::summarize(TotalPositive = sum(value))

data_processed_sum.ratio = merge(data_processed_sum.melt_total,data_processed_sum.melt,by='variable')
data_processed_sum.ratio[5] = NULL
data_processed_sum.ratio$Ratio = data_processed_sum.ratio$value / data_processed_sum.ratio$TotalPositive

data_processed_sum.ratio_info = data_processed_sum.ratio[,c('variable','Subcluster','Ratio')]
colnames(data_processed_sum.ratio_info) = c('variable','Subcluster','Ratio_Processed')

data_ratio = merge(data_raw_sum.ratio_info,data_processed_sum.ratio_info, by=c('variable','Subcluster'))
data_ratio$Ratio_Relative_Change = (data_ratio$Ratio_Processed - data_ratio$Ratio_Raw)/data_ratio$Ratio_Raw

data_ratio = data_ratio %>% mutate(Color = case_when(Ratio_Relative_Change > 0 ~ 'UP',
                                                 Ratio_Relative_Change < 0 ~ 'DOWN',
                                                 Ratio_Relative_Change == 0 ~ 'NONE'))

write_csv(data_ratio, "Subclusters_ratio_specificity.csv")

data_ratio$variable = factor(data_ratio$variable,
                             levels=c('CD4','CD8','CD3','CD45','CD279','Foxp3','GranzymeB','CD28','Ki67',
                             'CD68','CD163','HLADR','CD16','CD11b','CD66b','CD20','CD31','CK7','CD138'))
unique(data_ratio$Subcluster)

data_ratio$Subcluster = factor(data_ratio$Subcluster,
                               levels=c("CD3+ CD4+ T-cells","Resident memory CD4+ T-cells",
                                        "HLADR+ CD4+ Tregs","HLADR- CD4+ Tregs","Naive CD4+ T-cells",
                                        "PD1+ CD4+ T-cells","Activated CD4+ T-cells","CD16+ CD4+ T-cells",
                                        
                                        "CD3+ CD8+ T-cells","Proliferating CD8+ T-cells","PD1+CD28+ CD8+ T-cells",
                                        
                                        "M1 macrophages","M2 macrophages","Proliferating M1 macrophages",
                                        "Proliferating M2 macrophages","CD16+ M1 macrophages","CD16+ M2 macrophages",
                                        "HLADR+ M2 macrophages",
                                        
                                        "Classical monocytes","Intermediate monocytes","Activated monocytes",
                                        
                                        "B cells","Proliferating B cells","PD1+ B cells",
                                        
                                        "Neutrophils", "Plasma cells",
                                        
                                        "Cholangiocytes","Proliferating Cholangiocytes","HLADR+ Cholangiocytes",
                                        
                                        "Endothelial cells","Proliferating Endothelial cells","HLADR+ Endothelial cells",
                                        
                                        "Hepatocytes","Proliferating Hepatocytes","HLADR+ Hepatocytes"))


# T-cell markers
ggplot(data = (data_ratio %>% filter(variable %in% c('CD4','CD8','CD3','CD45'))),
                       aes(x = Subcluster, y = Ratio_Relative_Change,
                           fill=Color)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~variable, ncol=4) +
  ggtitle(NULL) + xlab("") + ylab("Relative change after pre-processing (%)") +
  theme(axis.text=element_text(size=8),
        axis.title=element_text(size=13),
        plot.title=element_text(size = 34, hjust = 0.5),
        panel.grid=element_blank(),
        legend.position='none',
        aspect.ratio=1.5,
        strip.text=element_text(size = 15, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  scale_x_discrete(limits=rev(levels(data_ratio$Subcluster)),
                   labels=rev(c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,
                                20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35))) +
  coord_flip() +
  geom_hline(yintercept = 0, color="black", lwd=1) +
  scale_fill_manual(values = c("gray","orange"))

ggplot(data = (data_ratio %>% filter(variable %in% c('Foxp3','GranzymeB','CD279','Ki67'))),
                       aes(x = Subcluster, y = Ratio_Relative_Change,
                           fill=Color)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~variable, ncol=4) +
  ggtitle(NULL) + xlab("") + ylab("Relative change after pre-processing (%)") +
  theme(axis.text=element_text(size=8),
        axis.title=element_text(size=13),
        plot.title=element_text(size = 34, hjust = 0.5),
        panel.grid=element_blank(),
        legend.position='none',
        aspect.ratio=1.5,
        strip.text=element_text(size = 15, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  scale_x_discrete(limits=rev(levels(data_ratio$Subcluster)),
                   labels=rev(c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,
                                20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35))) +
  coord_flip() +
  geom_hline(yintercept = 0, color="black", lwd=1) +
  scale_fill_manual(values = c("gray","orange"))

ggplot(data = (data_ratio %>% filter(variable %in% c('CD16','CD11b','HLADR'))),
                       aes(x = Subcluster, y = Ratio_Relative_Change,
                           fill=Color)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~variable, ncol=4) +
  ggtitle(NULL) + xlab("") + ylab("Relative change after pre-processing (%)") +
  theme(axis.text=element_text(size=8),
        axis.title=element_text(size=13),
        plot.title=element_text(size = 34, hjust = 0.5),
        panel.grid=element_blank(),
        legend.position='none',
        aspect.ratio=1.5,
        strip.text=element_text(size = 15, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  scale_x_discrete(limits=rev(levels(data_ratio$Subcluster)),
                   labels=rev(c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,
                                20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35))) +
  coord_flip() +
  geom_hline(yintercept = 0, color="black", lwd=1) +
  scale_fill_manual(values = c("gray","orange"))

ggplot(data = (data_ratio %>% filter(variable %in% c('CD28'))),
                       aes(x = Subcluster, y = Ratio_Relative_Change,
                           fill=Color)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~variable, ncol=4) +
  ggtitle(NULL) + xlab("") + ylab("Relative change after pre-processing (%)") +
  theme(axis.text=element_text(size=8),
        axis.title=element_text(size=13),
        plot.title=element_text(size = 34, hjust = 0.5),
        panel.grid=element_blank(),
        legend.position='none',
        aspect.ratio=1.5,
        strip.text=element_text(size = 15, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  scale_x_discrete(limits=rev(levels(data_ratio$Subcluster)),
                   labels=rev(c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,
                                20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35))) +
  coord_flip() +
  geom_hline(yintercept = 0, color="black", lwd=1) +
  scale_fill_manual(values = c("gray","orange"))


# Macrophage/Monocyte markers
data_ratio$variable = factor(data_ratio$variable,
                             levels=c('CD4','CD8','CD3','CD45','Foxp3','GranzymeB','CD28',
                             'CD68','CD163','HLADR','CD11b','CD16','Ki67','CD66b','CD20','CD279','CD31','CK7','CD138'))

data_ratio$Subcluster = factor(data_ratio$Subcluster,
                               levels=c("M1 macrophages","M2 macrophages","Proliferating M1 macrophages",
                                        "Proliferating M2 macrophages","CD16+ M1 macrophages","CD16+ M2 macrophages",
                                        "HLADR+ M2 macrophages",
                                        
                                        "Classical monocytes","Intermediate monocytes","Activated monocytes",
                                        
                                        "B cells","Proliferating B cells","PD1+ B cells",
                                        
                                        "CD3+ CD4+ T-cells","Resident memory CD4+ T-cells",
                                        "HLADR+ CD4+ Tregs","HLADR- CD4+ Tregs","Naive CD4+ T-cells",
                                        "PD1+ CD4+ T-cells","Activated CD4+ T-cells","CD16+ CD4+ T-cells",
                                        
                                        "CD3+ CD8+ T-cells","Proliferating CD8+ T-cells","PD1+CD28+ CD8+ T-cells",

                                        "Neutrophils", "Plasma cells",
                                        
                                        "Cholangiocytes","Proliferating Cholangiocytes","HLADR+ Cholangiocytes",
                                        
                                        "Endothelial cells","Proliferating Endothelial cells","HLADR+ Endothelial cells",
                                        
                                        "Hepatocytes","Proliferating Hepatocytes","HLADR+ Hepatocytes"))

ggplot(data = (data_ratio %>% filter(variable %in% c('CD68','CD163','CD16','HLADR','Ki67','CD11b'))),
                       aes(x = Subcluster, y = Ratio_Relative_Change,
                           fill=Color)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~variable, ncol=3) +
  ggtitle(NULL) + xlab("") + ylab("Relative change after pre-processing (%)") +
  theme(axis.text=element_text(size=8),
        axis.title=element_text(size=13),
        plot.title=element_text(size = 34, hjust = 0.5),
        panel.grid=element_blank(),
        legend.position='none',
        aspect.ratio=1.5,
        strip.text=element_text(size = 15, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  scale_x_discrete(limits=rev(levels(data_ratio$Subcluster))) +
  coord_flip() +
  geom_hline(yintercept = 0, color="black", lwd=1) +
  scale_fill_manual(values = c("gray","orange"))

# B-cell markers
ggplot(data = (data_ratio %>% filter(variable %in% c('CD20','CD279'))),
                       aes(x = Subcluster, y = Ratio_Relative_Change,
                           fill=Color)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~variable, ncol=1) +
  ggtitle(NULL) + xlab("") + ylab("Relative change after pre-processing (%)") +
  theme(axis.text=element_text(size=8),
        axis.title=element_text(size=13),
        plot.title=element_text(size = 34, hjust = 0.5),
        panel.grid=element_blank(),
        legend.position='none',
        aspect.ratio=1.5,
        strip.text=element_text(size = 15, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  scale_x_discrete(limits=rev(levels(data_ratio$Subcluster))) +
  coord_flip() +
  geom_hline(yintercept = 0, color="black", lwd=1) +
  scale_fill_manual(values = c("gray","orange"))


##################################################################################################
# For each subcluster: Calculate percentage of each marker that has a positive scaled expression #
##################################################################################################

## T-CELLS ONLY
tcell_raw = data_raw_sum.melt %>% 
  filter(Subcluster %in% unique(data_raw[data_raw$Clusters%in%c('CD4+ T-cells','CD8+ T-cells'),]$Subcluster))

tcell_raw$Perc_Positive = tcell_raw$value /  sum(tcell_raw$value) * 100

tcell_processed = data_processed_sum.melt %>% 
  filter(Subcluster %in% unique(data_processed[data_processed$Clusters%in%c('CD4+ T-cells','CD8+ T-cells'),]$Subcluster))

tcell_processed$Perc_Positive = tcell_processed$value /  sum(tcell_processed$value) * 100

tcell_sum = merge(tcell_raw,tcell_processed,by=c('Subcluster','variable'),all=T)
head(tcell_sum)

tcell_sum$Relative_Change = (tcell_sum$Perc_Positive.y - tcell_sum$Perc_Positive.x)/tcell_sum$Perc_Positive.x
head(tcell_sum)

tcell_sum$Subcluster = factor(tcell_sum$Subcluster,
                               levels=c("CD3+ CD4+ T-cells","Resident memory CD4+ T-cells",
                                        "HLADR+ CD4+ Tregs","HLADR- CD4+ Tregs","Naive CD4+ T-cells",
                                        "PD1+ CD4+ T-cells","Activated CD4+ T-cells","CD16+ CD4+ T-cells",
                                        "CD3+ CD8+ T-cells","PD1+CD28+ CD8+ T-cells","Proliferating CD8+ T-cells"))

tcell_sum$variable = factor(tcell_sum$variable,
                             levels=c('CD11b','CD16','HLADR','Ki67','CD279','CD28','GranzymeB',
                                      'Foxp3','CD45','CD3','CD8','CD4'))

ggplot((tcell_sum %>% 
          filter(variable %in% c('CD28','CD16','CD11b','CD45','CD8','CD4','CD279','Foxp3','Ki67','CD3','HLADR')) %>%
          filter(!is.na(Relative_Change))), 
       aes(Subcluster,variable, fill = Relative_Change, size = Perc_Positive.y)) +
  geom_point(shape = 21, stroke = 0) +
  scale_radius(range = c(5, 15)) +
  scale_fill_gradient2(high = "red",mid = "gray",low = "blue",midpoint = 0) +
  theme_bw() +
  scale_x_discrete(limits=rev(levels(cd4_sum$Subcluster))) +
  coord_flip() +
  theme(legend.position = "bottom", 
        panel.grid.major = element_blank(),
        axis.text=element_text(size=15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        axis.ticks = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  guides(size = guide_legend(override.aes = list(fill = NA, color = "black", stroke = .25), 
                             label.position = "bottom",
                             title.position = "right", 
                             order = 1),
         fill = guide_colorbar(ticks.colour = NA, title.position = "top", order = 2)) +
  labs(size = "Positive marker percentage\nin a cell phenotype in\npre-processed data (%)", 
       fill = "Relative change\nafter pre-processing (%)", x = NULL, y = NULL)

## MACRO, MONO, B CELL
mmb_raw = data_raw_sum.melt %>% 
  filter(Subcluster %in% unique(data_raw[data_raw$Clusters%in%c('Macrophages'),]$Subcluster))

mmb_raw$Perc_Positive = mmb_raw$value /  sum(mmb_raw$value) * 100

mmb_processed = data_processed_sum.melt %>% 
  filter(Subcluster %in% unique(data_processed[data_processed$Clusters%in%c('Macrophages'),]$Subcluster))

mmb_processed$Perc_Positive = mmb_processed$value /  sum(mmb_processed$value) * 100

mmb_sum = merge(mmb_raw,mmb_processed,by=c('Subcluster','variable'),all=T)
head(mmb_sum)

mmb_sum$Relative_Change = (mmb_sum$Perc_Positive.y - mmb_sum$Perc_Positive.x)/mmb_sum$Perc_Positive.x
head(mmb_sum)

mmb_sum$variable = factor(mmb_sum$variable,
                            levels=c('CD68','CD163','HLADR','CD11b','CD16','Ki67','CD20','CD279'))

mmb_sum$Subcluster = factor(mmb_sum$Subcluster,
                              levels=c('M1 macrophages','M2 macrophages','Proliferating M1 macrophages',
                            'Proliferating M2 macrophages',
                            'CD16+ M1 macrophages','CD16+ M2 macrophages',
                            'HLADR+ M2 macrophages',
                            'Classical monocytes','Intermediate monocytes','Activated monocytes',
                            'B cells','PD1+ B cells','Proliferating B cells'))

ggplot((mmb_sum %>% filter(variable %in% c('CD279','CD20','Ki67','CD16','CD11b','HLADR','CD163','CD68')) %>%
          filter(!is.na(Relative_Change))), 
       aes(Subcluster,variable, fill = Relative_Change, size = Perc_Positive.y)) +
  geom_point(shape = 21, stroke = 0) +
  scale_radius(range = c(5, 15)) +
  scale_fill_gradient2(high = "red",mid = "gray",low = "blue",midpoint = 0) +
  theme_bw() +
  scale_x_discrete(limits=rev(levels(macro_sum$Subcluster))) +
  coord_flip() +
  theme(legend.position = "bottom", 
        panel.grid.major = element_blank(),
        axis.text=element_text(size=15),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        axis.ticks = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  guides(size = guide_legend(override.aes = list(fill = NA, color = "black", stroke = .25), 
                             label.position = "bottom",
                             title.position = "right", 
                             order = 1),
         fill = guide_colorbar(ticks.colour = NA, title.position = "top", order = 2)) +
  labs(size = "Positive marker percentage\nin a cell phenotype in\npre-processed data (%)", 
       fill = "Relative change\nafter pre-processing (%)", x = NULL, y = NULL)
```

Subclusters - broken down by metacluster

```{r}
###################
###################
# CD4 SUBCLUSTERS #
###################
###################

###############################
# Change in cell % - boxplots #
###############################

cd4_cells_per_Patient_raw = data_raw %>% filter(Clusters=='CD4+ T-cells') %>%
  subset(select=c('Patient')) %>% group_by(Patient) %>% 
  dplyr::summarise(n = n())

cd4_cellType_per_Patient_raw = data_raw %>% filter(Clusters=='CD4+ T-cells') %>%
  subset(select=c('Patient','Subcluster')) %>%
  group_by(Patient,Subcluster) %>% dplyr::summarise(n = n())

cd4_cells_Patient_raw = merge(cd4_cells_per_Patient_raw, cd4_cellType_per_Patient_raw, all.x=TRUE, by='Patient')
head(cd4_cells_Patient_raw)
colnames(cd4_cells_Patient_raw) = c('Patient','CellTotal','Subcluster','Count')
cd4_cells_Patient_raw$Perc_CellType_Patient = cd4_cells_Patient_raw$Count / cd4_cells_Patient_raw$CellTotal
head(cd4_cells_Patient_raw)

cd4_cells_per_Patient_processed = data_processed %>% filter(Clusters=='CD4+ T-cells') %>%
  subset(select=c('Patient')) %>% group_by(Patient) %>% 
  dplyr::summarise(n = n())

cd4_cellType_per_Patient_processed = data_processed %>% filter(Clusters=='CD4+ T-cells') %>%
  subset(select=c('Patient','Subcluster')) %>%
  group_by(Patient,Subcluster) %>% dplyr::summarise(n = n())

cd4_cells_Patient_processed = merge(cd4_cells_per_Patient_processed, cd4_cellType_per_Patient_processed, all.x=TRUE, by='Patient')
head(cd4_cells_Patient_processed)
colnames(cd4_cells_Patient_processed) = c('Patient','CellTotal','Subcluster','Count')
cd4_cells_Patient_processed$Perc_CellType_Patient = cd4_cells_Patient_processed$Count / cd4_cells_Patient_processed$CellTotal
head(cd4_cells_Patient_processed)

cd4_cells_Patient_raw$Data='Raw'
cd4_cells_Patient_processed$Data='Processed'
cd4_Patient = rbind(cd4_cells_Patient_raw,cd4_cells_Patient_processed)
head(cd4_Patient)

cd4_Patient$Data = factor(cd4_Patient$Data, levels=c('Raw','Processed'))

shapiro.test((cd4_Patient)$Perc_CellType_Patient) # Reject Ho, data is non-normal - use non-parametric test
compare_means(Perc_CellType_Patient ~ Data, data = cd4_Patient, method='wilcox.test', group.by='Subcluster')

ggplot(data = cd4_Patient, 
               aes(x = Subcluster, y = Perc_CellType_Patient,fill=Data)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  ggtitle(NULL) + xlab(NULL) + ylab("Cell % per Patient\n(within CD4+ T-cell population)") +
  theme_bw() +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20),
        plot.title=element_text(size = 30, hjust = 0.5),
        legend.title=element_blank(),
        legend.text=element_text(size=25),
        aspect.ratio=1,
        panel.grid=element_blank(),
        strip.text=element_text(size = 28, hjust = 0.5),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits=c(0,1)) +
  scale_fill_manual(values=c('white','gray'))+
  scale_x_discrete(limits=c("CD3+ CD4+ T-cells","Resident memory CD4+ T-cells",
                            "HLADR+ CD4+ Tregs","HLADR- CD4+ Tregs", "Proliferating CD4+ T-cells",
                            "Naive CD4+ T-cells",
                            "PD1+ CD4+ T-cells","Activated CD4+ T-cells","CD16+ CD4+ T-cells"))


######################
# Median fold change #
######################

ccd4_raw_median = data_raw_median.melt %>% filter(Subcluster %in% unique(data_raw[data_raw$Clusters=='CD4+ T-cells',]$Subcluster))

cd4_processed_median = data_processed_median.melt %>% filter(Subcluster %in% unique(data_processed[data_processed$Clusters=='CD4+ T-cells',]$Subcluster))

cd4_median = merge(cd4_raw_median,cd4_processed_median,by=c('Subcluster','variable'))
head(cd4_median)
cd4_median$FC = cd4_median$value.y - cd4_median$value.x
head(cd4_median)

cd4_median$Subcluster = factor(cd4_median$Subcluster,
                               levels=c("CD3+ CD4+ T-cells","Resident memory CD4+ T-cells",
                                        "HLADR+ CD4+ Tregs","HLADR- CD4+ Tregs","Naive CD4+ T-cells",
                                        "PD1+ CD4+ T-cells","Activated CD4+ T-cells","CD16+ CD4+ T-cells"))

cd4_median$variable = factor(cd4_median$variable,
                             levels=c('CD4','CD8','CD3','CD45','Foxp3','GranzymeB','CD28','CD279','Ki67',
                             'CD68','CD163','HLADR','CD16','CD11b','CD66b','CD20','CD31','CK7','CD138'))

ggplot(data = (cd4_median %>% filter(variable %in% c('CD28','CD16','CD11b','CD45','CD4',
                                                  'CD279','Foxp3','Ki67','CD3','HLADR')) %>%
                 filter(!is.na(FC))),
       aes(x = FC, y = variable)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~Subcluster, ncol=4)+
  ggtitle(NULL) + ylab(NULL) + xlab("Median Fold Change") +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=30),
        plot.title=element_text(size = 34, hjust = 0.5),
        legend.position='none',
        panel.grid = element_blank(),
        aspect.ratio=1.7,
        strip.text=element_text(size = 13, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  geom_vline(xintercept = 0, color="black", lwd=1) +
  scale_x_continuous(breaks=c(-2,0,2,4,6,8,10)) +
  scale_y_discrete(limits=rev(levels(cd4_median$variable)))



###################
###################
# CD8 SUBCLUSTERS #
###################
###################

###############################
# Change in cell % - boxplots #
###############################

cd8_cells_per_Patient_raw = data_raw %>% filter(Clusters=='CD8+ T-cells') %>% 
  subset(select=c('Patient')) %>% group_by(Patient) %>% 
  dplyr::summarise(n = n())

cd8_cellType_per_Patient_raw = data_raw %>% filter(Clusters=='CD8+ T-cells') %>% 
  subset(select=c('Patient','Subcluster')) %>%
  group_by(Patient,Subcluster) %>% dplyr::summarise(n = n())

cd8_cells_Patient_raw = merge(cd8_cells_per_Patient_raw, cd8_cellType_per_Patient_raw, all.x=TRUE, by='Patient')
head(cd8_cells_Patient_raw)
colnames(cd8_cells_Patient_raw) = c('Patient','CellTotal','Subcluster','Count')
cd8_cells_Patient_raw$Perc_CellType_Patient = cd8_cells_Patient_raw$Count / cd8_cells_Patient_raw$CellTotal
head(cd8_cells_Patient_raw)

cd8_cells_per_Patient_processed = data_processed %>% filter(Clusters=='CD8+ T-cells') %>% 
  subset(select=c('Patient')) %>% group_by(Patient) %>% 
  dplyr::summarise(n = n())

cd8_cellType_per_Patient_processed = data_processed %>% filter(Clusters=='CD8+ T-cells') %>%
  subset(select=c('Patient','Subcluster')) %>%
  group_by(Patient,Subcluster) %>% dplyr::summarise(n = n())

cd8_cells_Patient_processed = merge(cd8_cells_per_Patient_processed, cd8_cellType_per_Patient_processed, all.x=TRUE, by='Patient')
head(cd8_cells_Patient_processed)
colnames(cd8_cells_Patient_processed) = c('Patient','CellTotal','Subcluster','Count')
cd8_cells_Patient_processed$Perc_CellType_Patient = cd8_cells_Patient_processed$Count / cd8_cells_Patient_processed$CellTotal
head(cd8_cells_Patient_processed)

cd8_cells_Patient_raw$Data='Raw'
cd8_cells_Patient_processed$Data='Processed'
cd8_Patient = rbind(cd8_cells_Patient_raw,cd8_cells_Patient_processed)
head(cd8_Patient)

cd8_Patient$Data = factor(cd8_Patient$Data, levels=c('Raw','Processed'))

cd8_Patient$Subcluster = factor(cd8_Patient$Subcluster,
                               levels=c("CD3+ CD8+ T-cells","Proliferating CD8+ T-cells","Cytotoxic T-cells",
                                        "PD1+ CD8+ T-cells","PD1+CD28+ CD8+ T-cells","CD16+CD28+ CD8+ T-cells"))

shapiro.test((cd8_Patient)$Perc_CellType_Patient) # Reject Ho, data is non-normal - use non-parametric test
compare_means(Perc_CellType_Patient ~ Data, data = cd8_Patient, method='wilcox.test', group.by='Subcluster')

ggplot(data = cd8_Patient, 
               aes(x = Subcluster, y = Perc_CellType_Patient,fill=Data)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  ggtitle(NULL) + xlab(NULL) + ylab("Cell % per Patient\n(within CD8+ T-cell population)") +
  theme_bw() +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20),
        plot.title=element_text(size = 30, hjust = 0.5),
        legend.title=element_blank(),
        legend.text=element_text(size=25),
        aspect.ratio=1,
        panel.grid=element_blank(),
        strip.text=element_text(size = 28, hjust = 0.5),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits=c(0,1)) +
  scale_fill_manual(values=c('white','gray'))


######################
# Median fold change #
######################

cd8_raw_median = data_raw_median.melt %>% filter(Subcluster %in% unique(data_raw[data_raw$Clusters=='CD8+ T-cells',]$Subcluster))

cd8_processed_median = data_processed_median.melt %>% filter(Subcluster %in% unique(data_processed[data_processed$Clusters=='CD8+ T-cells',]$Subcluster))

cd8_median = merge(cd8_raw_median,cd8_processed_median,by=c('Subcluster','variable'))
head(cd8_median)
cd8_median$FC = cd8_median$value.y - cd8_median$value.x
head(cd8_median)

ggplot(data = (cd8_median %>% filter(variable %in% c('CD28','CD16','CD11b','CD45','CD8','CD279','Foxp3',
                                           'Ki67','CD3','HLADR','GranzymeB')) %>%
                 filter(!is.na(FC))),
       aes(x = FC, y = variable)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~Subcluster)+
  ggtitle(NULL) + ylab(NULL) + xlab("Median Fold Change") +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=30),
        plot.title=element_text(size = 34, hjust = 0.5),
        legend.position='none',
        panel.grid = element_blank(),
        aspect.ratio=1,
        strip.text=element_text(size = 10, hjust = 0.5),
        axis.ticks = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  geom_vline(xintercept = 0, color="black", lwd=1) +
  scale_x_continuous(breaks=c(0,2,4,6,8,10))




##########################
##########################
# MACROPHAGE SUBCLUSTERS #
##########################
##########################

###############################
# Change in cell % - boxplots #
###############################

macro_cells_per_Patient_raw = data_raw %>% filter(Clusters=='Macrophages') %>% 
  subset(select=c('Patient')) %>% group_by(Patient) %>% 
  dplyr::summarise(n = n())

macro_cellType_per_Patient_raw = data_raw %>% filter(Clusters=='Macrophages') %>% 
  subset(select=c('Patient','Subcluster')) %>%
  group_by(Patient,Subcluster) %>% dplyr::summarise(n = n())

macro_cells_Patient_raw = merge(macro_cells_per_Patient_raw, macro_cellType_per_Patient_raw, all.x=TRUE, by='Patient')
head(macro_cells_Patient_raw)
colnames(macro_cells_Patient_raw) = c('Patient','CellTotal','Subcluster','Count')
macro_cells_Patient_raw$Perc_CellType_Patient = macro_cells_Patient_raw$Count / macro_cells_Patient_raw$CellTotal
head(macro_cells_Patient_raw)

macro_cells_per_Patient_processed = data_processed %>% filter(Clusters=='Macrophages') %>% 
  subset(select=c('Patient')) %>% group_by(Patient) %>% 
  dplyr::summarise(n = n())

macro_cellType_per_Patient_processed = data_processed %>% filter(Clusters=='Macrophages') %>%
  subset(select=c('Patient','Subcluster')) %>%
  group_by(Patient,Subcluster) %>% dplyr::summarise(n = n())

macro_cells_Patient_processed = merge(macro_cells_per_Patient_processed, macro_cellType_per_Patient_processed, all.x=TRUE, by='Patient')
head(macro_cells_Patient_processed)
colnames(macro_cells_Patient_processed) = c('Patient','CellTotal','Subcluster','Count')
macro_cells_Patient_processed$Perc_CellType_Patient = macro_cells_Patient_processed$Count / macro_cells_Patient_processed$CellTotal
head(macro_cells_Patient_processed)

macro_cells_Patient_raw$Data='Raw'
macro_cells_Patient_processed$Data='Processed'
macro_Patient = rbind(macro_cells_Patient_raw,macro_cells_Patient_processed)
head(macro_Patient)

macro_Patient$Data = factor(macro_Patient$Data, levels=c('Raw','Processed'))

shapiro.test((macro_Patient)$Perc_CellType_Patient) # Reject Ho, data is non-normal - use non-parametric test
compare_means(Perc_CellType_Patient ~ Data, data = macro_Patient, method='wilcox.test', group.by='Subcluster')

ggplot(data = macro_Patient, 
               aes(x = Subcluster, y = Perc_CellType_Patient,fill=Data)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  ggtitle(NULL) + xlab(NULL) + ylab("Cell % per Patient\n(within macrophage population)") +
  theme_bw() +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20),
        plot.title=element_text(size = 30, hjust = 0.5),
        legend.title=element_blank(),
        legend.text=element_text(size=25),
        aspect.ratio=1,
        panel.grid=element_blank(),
        strip.text=element_text(size = 28, hjust = 0.5),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits=c(0,1)) +
  scale_fill_manual(values=c('white','gray'))+
  scale_x_discrete(limits=c('M1 macrophages','M2 macrophages','Proliferating M1 macrophages',
                            'Proliferating M2 macrophages','CD11b+ M1 macrophages','CD11b+ M2 macrophages',
                            'CD16+ M1 macrophages','CD16+ M2 macrophages',
                            'HLADR+ M2 macrophages'))


######################
# Median fold change #
######################

macro_raw_median = data_raw_median.melt %>% filter(Subcluster %in% unique(data_raw[data_raw$Clusters=='Macrophages',]$Subcluster))

macro_processed_median = data_processed_median.melt %>% filter(Subcluster %in% unique(data_processed[data_processed$Clusters=='Macrophages',]$Subcluster))

macro_median = merge(macro_raw_median,macro_processed_median,by=c('Subcluster','variable'))
head(macro_median)
macro_median$FC = macro_median$value.y - macro_median$value.x
head(macro_median)

macro_median$variable = factor(macro_median$variable,
                            levels=c('CD68','CD163','HLADR','CD11b','CD16','Ki67'))

macro_median$Subcluster = factor(macro_median$Subcluster,
                              levels=c('M1 macrophages','M2 macrophages','Proliferating M1 macrophages',
                            'Proliferating M2 macrophages',
                            'CD16+ M1 macrophages','CD16+ M2 macrophages',
                            'HLADR+ M2 macrophages'))

ggplot(data = (macro_median %>% filter(variable %in% c('CD68','CD163','CD11b','HLADR','CD16','Ki67')) %>%
                 filter(!is.na(FC))),
       aes(x = FC, y = variable)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~Subcluster, ncol=4)+
  ggtitle(NULL) + ylab(NULL) + xlab("Median Fold Change") +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=30),
        plot.title=element_text(size = 34, hjust = 0.5),
        legend.position='none',
        panel.grid = element_blank(),
        aspect.ratio=1,
        strip.text=element_text(size = 13, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  geom_vline(xintercept = 0, color="black", lwd=1) +
  scale_x_continuous(breaks=c(-1,0,1),limits=c(-2,2)) +
  scale_y_discrete(limits=rev(levels(macro_median$variable)))




########################
########################
# MONOCYTE SUBCLUSTERS #
########################
########################

###############################
# Change in cell % - boxplots #
###############################

mono_cells_per_Patient_raw = data_raw %>% filter(Clusters=='Monocytes') %>% 
  subset(select=c('Patient')) %>% group_by(Patient) %>% 
  dplyr::summarise(n = n())

mono_cellType_per_Patient_raw = data_raw %>% filter(Clusters=='Monocytes') %>% 
  subset(select=c('Patient','Subcluster')) %>%
  group_by(Patient,Subcluster) %>% dplyr::summarise(n = n())

mono_cells_Patient_raw = merge(mono_cells_per_Patient_raw, mono_cellType_per_Patient_raw, all.x=TRUE, by='Patient')
head(mono_cells_Patient_raw)
colnames(mono_cells_Patient_raw) = c('Patient','CellTotal','Subcluster','Count')
mono_cells_Patient_raw$Perc_CellType_Patient = mono_cells_Patient_raw$Count / mono_cells_Patient_raw$CellTotal
head(mono_cells_Patient_raw)

mono_cells_per_Patient_processed = data_processed %>% filter(Clusters=='Monocytes') %>% 
  subset(select=c('Patient')) %>% group_by(Patient) %>% 
  dplyr::summarise(n = n())

mono_cellType_per_Patient_processed = data_processed %>% filter(Clusters=='Monocytes') %>%
  subset(select=c('Patient','Subcluster')) %>%
  group_by(Patient,Subcluster) %>% dplyr::summarise(n = n())

mono_cells_Patient_processed = merge(mono_cells_per_Patient_processed, mono_cellType_per_Patient_processed, all.x=TRUE, by='Patient')
head(mono_cells_Patient_processed)
colnames(mono_cells_Patient_processed) = c('Patient','CellTotal','Subcluster','Count')
mono_cells_Patient_processed$Perc_CellType_Patient = mono_cells_Patient_processed$Count / mono_cells_Patient_processed$CellTotal
head(mono_cells_Patient_processed)

mono_cells_Patient_raw$Data='Raw'
mono_cells_Patient_processed$Data='Processed'
mono_Patient = rbind(mono_cells_Patient_raw,mono_cells_Patient_processed)
head(mono_Patient)

mono_Patient$Data = factor(mono_Patient$Data, levels=c('Raw','Processed'))

shapiro.test((mono_Patient)$Perc_CellType_Patient) # Reject Ho, data is non-normal - use non-parametric test
compare_means(Perc_CellType_Patient ~ Data, data = mono_Patient, method='wilcox.test', group.by='Subcluster')

ggplot(data = mono_Patient, 
               aes(x = Subcluster, y = Perc_CellType_Patient,fill=Data)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  ggtitle(NULL) + xlab(NULL) + ylab("Cell % per Patient\n(within monocyte population)") +
  theme_bw() +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20),
        plot.title=element_text(size = 30, hjust = 0.5),
        legend.title=element_blank(),
        legend.text=element_text(size=25),
        aspect.ratio=1,
        panel.grid=element_blank(),
        strip.text=element_text(size = 28, hjust = 0.5),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits=c(0,1)) +
  scale_fill_manual(values=c('white','gray'))+
  scale_x_discrete(limits=c('Classical monocytes','Non-classical monocytes','Proliferating monocytes',
                            'Intermediate monocytes','Activated monocytes'))


######################
# Median fold change #
######################

mono_raw_median = data_raw_median.melt %>% filter(Subcluster %in% unique(data_raw[data_raw$Clusters=='Monocytes',]$Subcluster))

mono_processed_median = data_processed_median.melt %>% filter(Subcluster %in% unique(data_processed[data_processed$Clusters=='Monocytes',]$Subcluster))

mono_median = merge(mono_raw_median,mono_processed_median,by=c('Subcluster','variable'))
head(mono_median)
mono_median$FC = mono_median$value.y - mono_median$value.x
head(mono_median)

mono_median$variable = factor(mono_median$variable,
                              levels=c('CD11b','CD16','Ki67','HLADR','CD68','CD163'))

ggplot(data = (mono_median %>% filter(variable %in% c('CD68','CD163','CD11b','HLADR','CD16','Ki67')) %>%
                 filter(!is.na(FC))),
       aes(x = FC, y = variable)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~Subcluster, ncol=4)+
  ggtitle(NULL) + ylab(NULL) + xlab("Median Fold Change") +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=30),
        plot.title=element_text(size = 34, hjust = 0.5),
        legend.position='none',
        panel.grid = element_blank(),
        aspect.ratio=1,
        strip.text=element_text(size = 13, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  geom_vline(xintercept = 0, color="black", lwd=1) +
  scale_x_continuous(breaks=c(-1,0,1,2),limits=c(-1,2)) +
  scale_y_discrete(limits=rev(levels(mono_median$variable)))




######################
######################
# B CELL SUBCLUSTERS #
######################
######################

###############################
# Change in cell % - boxplots #
###############################

b_cells_per_Patient_raw = data_raw %>% filter(Clusters=='B cells') %>% 
  subset(select=c('Patient')) %>% group_by(Patient) %>% 
  dplyr::summarise(n = n())

b_cellType_per_Patient_raw = data_raw %>% filter(Clusters=='B cells') %>% 
  subset(select=c('Patient','Subcluster')) %>%
  group_by(Patient,Subcluster) %>% dplyr::summarise(n = n())

b_cells_Patient_raw = merge(b_cells_per_Patient_raw, b_cellType_per_Patient_raw, all.x=TRUE, by='Patient')
head(b_cells_Patient_raw)
colnames(b_cells_Patient_raw) = c('Patient','CellTotal','Subcluster','Count')
b_cells_Patient_raw$Perc_CellType_Patient = b_cells_Patient_raw$Count / b_cells_Patient_raw$CellTotal
head(b_cells_Patient_raw)

b_cells_per_Patient_processed = data_processed %>% filter(Clusters=='B cells') %>% 
  subset(select=c('Patient')) %>% group_by(Patient) %>% 
  dplyr::summarise(n = n())

b_cellType_per_Patient_processed = data_processed %>% filter(Clusters=='B cells') %>%
  subset(select=c('Patient','Subcluster')) %>%
  group_by(Patient,Subcluster) %>% dplyr::summarise(n = n())

b_cells_Patient_processed = merge(b_cells_per_Patient_processed, b_cellType_per_Patient_processed, all.x=TRUE, by='Patient')
head(b_cells_Patient_processed)
colnames(b_cells_Patient_processed) = c('Patient','CellTotal','Subcluster','Count')
b_cells_Patient_processed$Perc_CellType_Patient = b_cells_Patient_processed$Count / b_cells_Patient_processed$CellTotal
head(b_cells_Patient_processed)

b_cells_Patient_raw$Data='Raw'
b_cells_Patient_processed$Data='Processed'
b_Patient = rbind(b_cells_Patient_raw,b_cells_Patient_processed)
head(b_Patient)

b_Patient$Data = factor(b_Patient$Data, levels=c('Raw','Processed'))

shapiro.test((b_Patient)$Perc_CellType_Patient) # Reject Ho, data is non-normal - use non-parametric test
compare_means(Perc_CellType_Patient ~ Data, data = b_Patient, method='wilcox.test', group.by='Subcluster')

ggplot(data = b_Patient, 
               aes(x = Subcluster, y = Perc_CellType_Patient,fill=Data)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  ggtitle(NULL) + xlab(NULL) + ylab("Cell % per Patient\n(within B cell population)") +
  theme_bw() +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20),
        plot.title=element_text(size = 30, hjust = 0.5),
        legend.title=element_blank(),
        legend.text=element_text(size=25),
        aspect.ratio=1,
        panel.grid=element_blank(),
        strip.text=element_text(size = 28, hjust = 0.5),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits=c(0,1)) +
  scale_fill_manual(values=c('white','gray'))+
  scale_x_discrete(limits=c("B cells","Proliferating B cells","PD1+ B cells"))


######################
# Median fold change #
######################

b_raw_median = data_raw_median.melt %>% filter(Subcluster %in% unique(data_raw[data_raw$Clusters=='B cells',]$Subcluster))

b_processed_median = data_processed_median.melt %>% filter(Subcluster %in% unique(data_processed[data_processed$Clusters=='B cells',]$Subcluster))

b_median = merge(b_raw_median,b_processed_median,by=c('Subcluster','variable'))
head(b_median)
b_median$FC = b_median$value.y - b_median$value.x
head(b_median)

b_median$variable = factor(b_median$variable,
                           levels=c('CD20','HLADR','Ki67','CD279'))

b_median$Subcluster = factor(b_median$Subcluster,
                             levels=c('B cells','Proliferating B cells','PD1+ B cells'))

ggplot(data = (b_median %>% filter(variable %in% c('CD279','CD20','Ki67','HLADR')) %>%
                 filter(!is.na(FC))),
       aes(x = FC, y = variable)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  facet_wrap(~Subcluster, ncol=4)+
  ggtitle(NULL) + ylab(NULL) + xlab("Median Fold Change") +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=30),
        plot.title=element_text(size = 34, hjust = 0.5),
        legend.position='none',
        panel.grid = element_blank(),
        aspect.ratio=1,
        strip.text=element_text(size = 13, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  geom_vline(xintercept = 0, color="black", lwd=1) +
  scale_y_discrete(limits=rev(levels(b_median$variable)))
```


# QUANTIFY CELLS WITH MIXED PHENOTYPE AS WELL AS NOISE IN DATA (aka labelled as Hepatocytes by exclusion)

RAW

```{r}
raw = read_steinbock(path="~/Google Drive/My Drive/Emamaullee Lab Data.gdrive/Method Paper/Raw data",
                             intensities_folder = "intensities",
                             regionprops_folder = "regionprops",
                             graphs_folder = "neighbors",
                             pattern = NULL,
                             extract_cellid_from = "Object",
                             extract_coords_from = c("centroid-1", "centroid-0"),
                             image_file = "images.csv",
                             extract_imagemetadata_from = c("width_px", "height_px"),
                             panel_file = "panel.csv",
                             extract_names_from = "name",
                             return_as = "sce")
assay(raw, "exprs") = asinh(counts(raw)/5)
assay(raw,'exprs') = t(scale(t(assay(raw,'exprs'))))

markers_to_include = c('CD66b','CD20','CD28','CD16','CD163','CD11b','CD45',
                       'CD4','CD31','CD279','CD68','FoxP3',
                       'CK7','Ki67','CD8',
                       'CD3','CD138','HLADR','GranzymeB')


raw_scaled = as.data.frame((t(assay(raw[rownames(raw) %in% markers_to_include,],'exprs'))))
head(raw_scaled)

raw_scaled = raw_scaled[ ,c('CD4','CD8','CD20','CD11b','CD68','CD163','CD66b','CD31','CK7','CD138',
                                             'CD28','CD16','CD45',
                                             'CD279','FoxP3','Ki67',
                                             'CD3','HLADR','GranzymeB')]
head(raw_scaled)

raw_scaled %>% summary()

# Identify lineage marker as well as top 3 highest expressing markers for each cell
maxn = function(n) function(x) base::order(x, decreasing = TRUE)[!is.na(x)][n]
raw_scaled = raw_scaled %>%
  mutate(Lineage=apply(.[1:10], 1, function(x) names(x)[maxn(1)(x)]))
raw_scaled = raw_scaled %>%
  mutate(Highest=apply(.[1:19], 1, function(x) names(x)[maxn(1)(x)]))
raw_scaled = raw_scaled %>%
  mutate(Second_Highest=apply(.[1:19], 1, function(x) names(x)[maxn(2)(x)]))
raw_scaled = raw_scaled %>%
  mutate(Third_Highest=apply(.[1:19], 1, function(x) names(x)[maxn(3)(x)]))

head(raw_scaled)
```

PRE-PROCESSED

```{r}
processed = imcRtools::read_steinbock(path="/users/sarahbangerth/Desktop/IMC/Adult IMC Output/Data/Final/Mesmer",
                             intensities_folder = "intensities",
                             regionprops_folder = "regionprops",
                             graphs_folder = "neighbors",
                             pattern = NULL,
                             extract_cellid_from = "Object",
                             extract_coords_from = c("centroid-1", "centroid-0"),
                             image_file = "images.csv",
                             extract_imagemetadata_from = c("width_px", "height_px"),
                             panel_file = "panel.csv",
                             extract_names_from = "name",
                             return_as = "sce")
assay(processed, "exprs") = asinh(counts(processed)/5)
assay(processed,'exprs') = t(scale(t(assay(processed,'exprs'))))

markers_to_include = c('CD66b','CD20','CD28','CD16','CD163','CD11b','CD45',
                       'CD4','CD31','CD279','CD68','Foxp3',
                       'CK7','Ki67','CD8',
                       'CD3','CD138','HLADR','GranzymeB')


processed_scaled = as.data.frame((t(assay(processed[rownames(processed) %in%  markers_to_include,],'exprs'))))
head(processed_scaled)

processed_scaled = processed_scaled[,c('CD4','CD8','CD20','CD11b','CD68','CD163','CD66b','CD31','CK7','CD138', #Lineage
                                             'CD28','CD16','CD45',
                                             'CD279','Foxp3','Ki67',
                                             'CD3','HLADR','GranzymeB')]
head(processed_scaled)

processed_scaled %>% summary()

# Identify lineage marker as well as top 3 highest expressing markers for each cell
maxn = function(n) function(x) base::order(x, decreasing = TRUE)[!is.na(x)][n]
processed_scaled = processed_scaled %>%
  mutate(Lineage=apply(.[1:10], 1, function(x) names(x)[maxn(1)(x)]))
processed_scaled = processed_scaled %>%
  mutate(Highest=apply(.[1:19], 1, function(x) names(x)[maxn(1)(x)]))
processed_scaled = processed_scaled %>%
  mutate(Second_Highest=apply(.[1:19], 1, function(x) names(x)[maxn(2)(x)]))
processed_scaled = processed_scaled %>%
  mutate(Third_Highest=apply(.[1:19], 1, function(x) names(x)[maxn(3)(x)]))

head(processed_scaled)
```

Compare cells with mixed phenotype

```{r}
###############
# B & T cells #
###############

dim(raw_scaled[((raw_scaled$Highest %in% c('CD4','CD8'))&
                    ((raw_scaled$Second_Highest == 'CD20')))|
                   ((raw_scaled$Second_Highest %in% c('CD4','CD8'))&
                      ((raw_scaled$Highest == 'CD20'))),])
2964/402287 # 0.7%

dim(processed_scaled[((processed_scaled$Highest %in% c('CD4','CD8'))&
                    ((processed_scaled$Second_Highest == 'CD20')))|
                   ((processed_scaled$Second_Highest %in% c('CD4','CD8'))&
                      ((processed_scaled$Highest == 'CD20'))),])

875/461816 # 0.2%

(0.001894694-0.007367874)/0.007367874 # -74.3%

########################
# Macrophage & T cells #
########################

dim(raw_scaled[((raw_scaled$Highest %in% c('CD4','CD8'))&
                    ((raw_scaled$Second_Highest == 'CD68')))|
                   ((raw_scaled$Second_Highest %in% c('CD4','CD8'))&
                      ((raw_scaled$Highest == 'CD68'))),])
3714/402287 # 0.9%

dim(processed_scaled[((processed_scaled$Highest %in% c('CD4','CD8'))&
                    ((processed_scaled$Second_Highest == 'CD68')))|
                   ((processed_scaled$Second_Highest %in% c('CD4','CD8'))&
                      ((processed_scaled$Highest == 'CD68'))),])

3458/461816 # 0.7%

(0.007487831-0.009232215)/0.009232215 # -18.9%

########################
# Macrophage & B cells #
########################

dim(raw_scaled[((raw_scaled$Highest %in% c('CD20'))&
                    ((raw_scaled$Second_Highest %in% c('CD68'))))|
                   ((raw_scaled$Second_Highest %in% c('CD20'))&
                      ((raw_scaled$Highest %in% c('CD68')))),])
1353/402287 # 0.3%

dim(processed_scaled[((processed_scaled$Highest %in% c('CD20'))&
                    ((processed_scaled$Second_Highest %in% c('CD68'))))|
                   ((processed_scaled$Second_Highest %in% c('CD20'))&
                      ((processed_scaled$Highest %in% c('CD68')))),])

87/461816 # 0.02%

(0.0001883867-0.003363271)/0.003363271 #-94.4%

#################
# CD3 & B cells #
#################

dim(raw_scaled[((raw_scaled$Highest %in% c('CD20'))&
                    ((raw_scaled$Second_Highest %in% c('CD3'))))|
                   ((raw_scaled$Second_Highest %in% c('CD20'))&
                      ((raw_scaled$Highest %in% c('CD3')))),])
690/402287 # 0.2%

dim(processed_scaled[((processed_scaled$Highest %in% c('CD20'))&
                    ((processed_scaled$Second_Highest %in% c('CD3'))))|
                   ((processed_scaled$Second_Highest %in% c('CD20'))&
                      ((processed_scaled$Highest %in% c('CD3')))),])

590/461816 # 0.1%

(0.001277565-0.001715193)/0.001715193 #-25.5%

####################
# Neutro & B cells #
####################

dim(raw_scaled[((raw_scaled$Highest %in% c('CD20'))&
                    ((raw_scaled$Second_Highest %in% c('CD66b'))))|
                   ((raw_scaled$Second_Highest %in% c('CD20'))&
                      ((raw_scaled$Highest %in% c('CD66b')))),])
3513/402287 # 0.9%

dim(processed_scaled[((processed_scaled$Highest %in% c('CD20'))&
                    ((processed_scaled$Second_Highest %in% c('CD66b'))))|
                   ((processed_scaled$Second_Highest %in% c('CD20'))&
                      ((processed_scaled$Highest %in% c('CD66b')))),])

330/461816 # 0.07%

(0.0007145703-0.008732572)/0.008732572 #-91.8%
```

```{r}
df = as.data.frame(c('T/B cells','T cells/Macrophages','Macrophages/B cells','Neutrophils/B cells','CD3/B cells'))
colnames(df) = 'Comparison'
df$Raw = c(0.007367874, 0.009232215, 0.003363271, 0.008732572, 0.001715193)
df$Processed = c(0.001894694, 0.007487831, 0.0001883867, 0.0007145703, 0.001277565)
df$RelativeChange = c((0.001894694-0.007367874)/0.007367874, (0.007487831-0.009232215)/0.009232215,
                      (0.0001883867-0.003363271)/0.003363271, (0.0007145703-0.008732572)/0.008732572,
                      (0.001277565-0.001715193)/0.001715193)
df


df_melt = melt(df, id.vars = c('Comparison'), measure.vars = c('Raw','Processed','RelativeChange'))

head(df_melt)

df_melt$variable = factor(df_melt$variable,levels=c('Raw','Processed','RelativeChange'))

ggplot(data = df_melt[df_melt$variable == 'RelativeChange',], aes(x = Comparison, y = value, fill=variable)) +
  geom_col(position = position_dodge(width = 0.8), width=0.8) +
  theme_bw() +
  ggtitle(NULL) + xlab(NULL) + ylab("Relative Change (%)") +
  theme(axis.text=element_text(size=25),
        axis.title=element_text(size=30),
        plot.title=element_text(size = 34, hjust = 0.5),
        legend.position='none',
        panel.grid = element_blank(),
        legend.title=element_blank(),
        legend.text=element_text(size=45),
        aspect.ratio=1,
        strip.text=element_text(size = 34, hjust = 0.5),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits=c(-1,0)) +
  coord_flip() +
  geom_hline(yintercept = 0) +
  scale_fill_manual(values=c('gray'))

```

